apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - args:
    - echo 'hello';sleep 2d
    command:
    - /bin/bash
    - -c
    image: harbor.ail.unisound.com/zhanghui/tensorflow-cpu-1.2.1:latest 
    imagePullPolicy: IfNotPresent
    name: demo
    volumeMounts:
    - mountPath: /gfs
      name: nfs0
    - mountPath: '/tmp'
      name: hostpath1
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  volumes:
  - name: nfs0
    nfs:
      path: "/volume1/gfs"
      server: 10.10.10.251
      readOnly: false
  - hostPath:
      path: /tmp
    name: hostpath1
